Parameters:
  Username:
    NoEcho: true
    Description: Username for Aurora MySQL database access
    Type: String
    MinLength: '1'
    MaxLength: '16'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters.
  Password:
    NoEcho: true
    Description: Password for Aurora MySQL database access
    Type: String
    MinLength: '8'
    MaxLength: '41'
    AllowedPattern: '[a-zA-Z0-9]*'
    ConstraintDescription: must contain only alphanumeric characters.

Resources:
  AuroraDBCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      Engine: aurora-mysql
      MasterUsername: !Ref Username
      MasterUserPassword: !Ref Password
      DatabaseName: UnaxedDB
      DBClusterIdentifier: Unaxed-DB-Cluster
      DBClusterParameterGroupName: !Ref RDSDBClusterParameterGroup
      EnableIAMDatabaseAuthentication: true

  AuroraDBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBClusterIdentifier: !Ref AuroraDBCluster
      Engine: aurora-mysql
      DBInstanceClass: db.t3.medium
      PubliclyAccessible: true

  RDSDBClusterParameterGroup:
    Type: AWS::RDS::DBClusterParameterGroup
    Properties:
      Description: CloudFormation Sample Aurora Cluster Parameter Group
      Family: aurora-mysql8.0
      Parameters:
        time_zone: US/Eastern

  RDSDBParameterGroup:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      Description: CloudFormation Sample Aurora Parameter Group
      Family: aurora-mysql8.0
      Parameters:
        sql_mode: IGNORE_SPACE
        max_allowed_packet: '1024'
        innodb_buffer_pool_size: "{DBInstanceClassMemory*3/4}"

Outputs:
  AuroraEndpoint:
    Description: The endpoint for the Aurora Cluster
    Value: !GetAtt [AuroraDBCluster, Endpoint.Address]
