interface ProfileFormInterface {
    fullName: string,
    title: string,
    company?: string,
    bio?: string,
    country: string,
    password: string,
    confirmPassword: string,
    profileImage?: string,
    coverImage?: string,
    socialLinks?: {
        facebook?: string,
        twitter?: string,
        linkedIn?: string,
        instagram?: string,
        github?: string,
        website?: string,
    },
    skills?: string[],
    interests?: string[],
    languages?: string[],
    certifications?: string[],
    education?: {
        school: string,
        degree: string,
        fieldOfStudy: string,
        startYear: number,
        endYear: number,
        grade: string,
        activities: string,
        description: string,
    }[],
    experience?: {
        title: string,
        company: string,
        location: string,
        startYear: number,
        endYear: number,
        description: string,
    }[],
    projects?: {
        title: string,
        description: string,
        link: string,
        image: string,
    }[],
}

export type { ProfileFormInterface };